server:
  port: 9086  # 使用不同于原服务的端口
spring:
  application:
    name: team-construction-service # 新服务名称
  cloud:
    nacos:
      server-addr: 8.217.163.166:8848/nacos  # 保持原 Nacos 地址不变
      username: nacos
      password: nacos
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${hm.db.host}:3306/university?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${hm.db.pw}  # 使用与原项目相同的密码配置方式
  redis:
    sentinel:
      master: hmaster # 集群名
      nodes: # 哨兵地址列表
        - 8.217.163.166:27001
        - 8.217.163.166:27002
        - 8.217.163.166:27003

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

logging:
  level:
    com.hmall.personnel: debug  # 调整为新服务的包名
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"

hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /personnel/**  # 新服务的公共接口路径
