server:
  port: 8086  # 使用不同于原服务的端口
spring:
  application:
    name: personnel-management-service  # 新服务名称
  cloud:
    nacos:
      server-addr: 192.168.43.130:8848  # 保持原 Nacos 地址不变
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${hm.db.host}:3306/university_personnel_management?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${hm.db.pw}  # 使用与原项目相同的密码配置方式
  redis:
    host: 192.168.43.130  # 使用原项目的 Redis 地址
    port: 6379
    password:  # 如果 Redis 有密码，需要在这里配置

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

logging:
  level:
    com.hmall.personnel: debug  # 调整为新服务的包名
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"

knife4j:
  enable: true
  openapi:
    title: 教职工档案管理服务接口文档
    description: "教职工档案管理服务接口文档"
    email: zhanghuyi@itcast.cn
    contact: 虎哥  # 修正原配置中的拼写错误（concat -> contact）
    url: https://www.itcast.cn
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.hmall.personnel.controller  # 调整为新服务的控制器包名

hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /personnel/public/**  # 新服务的公共接口路径
      - /login
      - /swagger-ui/**
      - /v3/api-docs/**